volumes:
  surrealdb:

services:
  init-data:
    image: busybox
    command: chmod -R 777 /data
    volumes:
      - surrealdb:/data
  election_surrealdb:
    image: surrealdb/surrealdb:v2
    command: start --user root --pass root rocksdb:/mydata/mydatabase.db
    volumes:
      - surrealdb:/mydata
    healthcheck:
      test: ["CMD-SHELL", "surreal", "-V"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      init-data:
        condition: service_completed_successfully
    ports:
      - 8000:8000
