export const TABLE_DEFINITIONS = [
  "DEFINE TABLE organization TYPE NORMAL SCHEMAFULL;",
  "DEFINE FIELD name ON organization TYPE string;",
  "DEFINE FIELD slug ON organization TYPE string;",
  "DEFINE FIELD createdAt ON organization TYPE datetime DEFAULT time::now();",

  "DEFINE TABLE project TYPE NORMAL SCHEMAFULL;",
  "DEFINE FIELD organizationId ON project TYPE record<organization>;",
  "DEFINE FIELD name ON project TYPE string;",
  "DEFINE FIELD code ON project TYPE string;",
  `DEFINE FIELD type ON project TYPE string ASSERT $value IN ["client", "internal"];`,
  `DEFINE FIELD status ON project TYPE string DEFAULT "active" ASSERT $value IN ["active", "archived"];`,
  "DEFINE FIELD metadata ON project TYPE object FLEXIBLE;",
  "DEFINE FIELD createdAt ON project TYPE datetime DEFAULT time::now();",

  "DEFINE TABLE canonical_user TYPE NORMAL SCHEMAFULL;",
  "DEFINE FIELD organizationId ON canonical_user TYPE record<organization>;",
  "DEFINE FIELD displayName ON canonical_user TYPE string;",
  "DEFINE FIELD primaryEmail ON canonical_user TYPE option<string>;",
  `DEFINE FIELD role ON canonical_user TYPE string DEFAULT "member" ASSERT $value IN ["admin", "manager", "member"];`,
  "DEFINE FIELD active ON canonical_user TYPE bool DEFAULT true;",
  "DEFINE FIELD passwordHash ON canonical_user TYPE string;",
  "DEFINE FIELD createdAt ON canonical_user TYPE datetime DEFAULT time::now();",

  "DEFINE TABLE external_identity TYPE NORMAL SCHEMAFULL;",
  "DEFINE FIELD organizationId ON external_identity TYPE record<organization>;",
  `DEFINE FIELD source ON external_identity TYPE string ASSERT $value IN ["git", "plane", "discord"];`,
  "DEFINE FIELD externalId ON external_identity TYPE string;",
  "DEFINE FIELD username ON external_identity TYPE option<string>;",
  "DEFINE FIELD email ON external_identity TYPE option<string>;",
  "DEFINE FIELD displayName ON external_identity TYPE option<string>;",
  "DEFINE FIELD canonicalUserId ON external_identity TYPE option<record<canonical_user>>;",
  "DEFINE FIELD confidence ON external_identity TYPE option<float>;",
  `DEFINE FIELD status ON external_identity TYPE string DEFAULT "unmatched" ASSERT $value IN ["matched", "suggested", "unmatched", "ignored"];`,
  "DEFINE FIELD createdAt ON external_identity TYPE datetime DEFAULT time::now();",

  "DEFINE TABLE integration_connection TYPE NORMAL SCHEMAFULL;",
  "DEFINE FIELD organizationId ON integration_connection TYPE record<organization>;",
  `DEFINE FIELD source ON integration_connection TYPE string ASSERT $value IN ["git", "plane", "discord"];`,
  "DEFINE FIELD name ON integration_connection TYPE string;",
  `DEFINE FIELD status ON integration_connection TYPE string DEFAULT "active" ASSERT $value IN ["active", "paused", "error"];`,
  "DEFINE FIELD configRef ON integration_connection TYPE string;",
  "DEFINE FIELD createdAt ON integration_connection TYPE datetime DEFAULT time::now();",

  "DEFINE TABLE source_mapping TYPE NORMAL SCHEMAFULL;",
  "DEFINE FIELD organizationId ON source_mapping TYPE record<organization>;",
  `DEFINE FIELD source ON source_mapping TYPE string ASSERT $value IN ["git", "plane", "discord"];`,
  `DEFINE FIELD externalScopeType ON source_mapping TYPE string ASSERT $value IN ["repo", "workspace", "board", "channel", "server"];`,
  "DEFINE FIELD externalScopeId ON source_mapping TYPE string;",
  "DEFINE FIELD projectId ON source_mapping TYPE record<project>;",
  "DEFINE FIELD confidence ON source_mapping TYPE float DEFAULT 1.0;",
  `DEFINE FIELD mappingType ON source_mapping TYPE string ASSERT $value IN ["manual", "rule", "inferred"];`,

  "DEFINE TABLE raw_event_payload TYPE NORMAL SCHEMAFULL;",
  "DEFINE FIELD organizationId ON raw_event_payload TYPE record<organization>;",
  "DEFINE FIELD source ON raw_event_payload TYPE string;",
  "DEFINE FIELD connectionId ON raw_event_payload TYPE record<integration_connection>;",
  "DEFINE FIELD externalEventId ON raw_event_payload TYPE string;",
  "DEFINE FIELD receivedAt ON raw_event_payload TYPE datetime DEFAULT time::now();",
  "DEFINE FIELD payload ON raw_event_payload TYPE object FLEXIBLE;",
  "DEFINE FIELD checksum ON raw_event_payload TYPE string;",

  "DEFINE TABLE normalized_event TYPE NORMAL SCHEMAFULL;",
  "DEFINE FIELD organizationId ON normalized_event TYPE record<organization>;",
  "DEFINE FIELD source ON normalized_event TYPE string;",
  "DEFINE FIELD sourceEventType ON normalized_event TYPE string;",
  "DEFINE FIELD eventTime ON normalized_event TYPE datetime;",
  "DEFINE FIELD ingestedAt ON normalized_event TYPE datetime DEFAULT time::now();",
  "DEFINE FIELD externalIdentityId ON normalized_event TYPE option<record<external_identity>>;",
  "DEFINE FIELD canonicalUserId ON normalized_event TYPE option<record<canonical_user>>;",
  "DEFINE FIELD projectId ON normalized_event TYPE option<record<project>>;",
  "DEFINE FIELD sourceRef ON normalized_event TYPE object FLEXIBLE;",
  "DEFINE FIELD content ON normalized_event TYPE object FLEXIBLE;",
  "DEFINE FIELD attribution ON normalized_event TYPE object FLEXIBLE;",
  "DEFINE FIELD processingVersion ON normalized_event TYPE int DEFAULT 1;",

  "DEFINE TABLE activity_session TYPE NORMAL SCHEMAFULL;",
  "DEFINE FIELD organizationId ON activity_session TYPE record<organization>;",
  "DEFINE FIELD canonicalUserId ON activity_session TYPE record<canonical_user>;",
  "DEFINE FIELD startedAt ON activity_session TYPE datetime;",
  "DEFINE FIELD endedAt ON activity_session TYPE datetime;",
  "DEFINE FIELD eventIds ON activity_session TYPE array;",
  "DEFINE FIELD projectIds ON activity_session TYPE array;",
  "DEFINE FIELD confidence ON activity_session TYPE float;",

  "DEFINE TABLE activity_cluster TYPE NORMAL SCHEMAFULL;",
  "DEFINE FIELD organizationId ON activity_cluster TYPE record<organization>;",
  "DEFINE FIELD canonicalUserId ON activity_cluster TYPE record<canonical_user>;",
  "DEFINE FIELD projectId ON activity_cluster TYPE option<record<project>>;",
  "DEFINE FIELD sessionId ON activity_cluster TYPE option<record<activity_session>>;",
  "DEFINE FIELD eventIds ON activity_cluster TYPE array;",
  "DEFINE FIELD topicLabel ON activity_cluster TYPE option<string>;",
  "DEFINE FIELD clusterType ON activity_cluster TYPE string;",
  "DEFINE FIELD startedAt ON activity_cluster TYPE datetime;",
  "DEFINE FIELD endedAt ON activity_cluster TYPE datetime;",
  "DEFINE FIELD confidence ON activity_cluster TYPE float;",

  "DEFINE TABLE work_unit TYPE NORMAL SCHEMAFULL;",
  "DEFINE FIELD organizationId ON work_unit TYPE record<organization>;",
  "DEFINE FIELD canonicalUserId ON work_unit TYPE record<canonical_user>;",
  "DEFINE FIELD projectId ON work_unit TYPE record<project>;",
  "DEFINE FIELD date ON work_unit TYPE string;",
  "DEFINE FIELD title ON work_unit TYPE string;",
  "DEFINE FIELD summary ON work_unit TYPE string;",
  "DEFINE FIELD evidenceEventIds ON work_unit TYPE array;",
  "DEFINE FIELD startedAt ON work_unit TYPE datetime;",
  "DEFINE FIELD endedAt ON work_unit TYPE datetime;",
  "DEFINE FIELD estimatedMinutes ON work_unit TYPE int;",
  "DEFINE FIELD sourceTypes ON work_unit TYPE array;",
  "DEFINE FIELD confidence ON work_unit TYPE float;",
  `DEFINE FIELD reviewStatus ON work_unit TYPE string DEFAULT "draft" ASSERT $value IN ["draft", "reviewed", "approved", "flagged"];`,
  "DEFINE FIELD generationVersion ON work_unit TYPE int DEFAULT 1;",

  "DEFINE TABLE daily_summary TYPE NORMAL SCHEMAFULL;",
  "DEFINE FIELD organizationId ON daily_summary TYPE record<organization>;",
  `DEFINE FIELD scopeType ON daily_summary TYPE string ASSERT $value IN ["user", "project"];`,
  "DEFINE FIELD scopeId ON daily_summary TYPE record;",
  "DEFINE FIELD date ON daily_summary TYPE string;",
  "DEFINE FIELD summary ON daily_summary TYPE string;",
  "DEFINE FIELD workUnitIds ON daily_summary TYPE array;",
  "DEFINE FIELD generatedAt ON daily_summary TYPE datetime DEFAULT time::now();",
  `DEFINE FIELD status ON daily_summary TYPE string DEFAULT "draft" ASSERT $value IN ["draft", "reviewed", "approved"];`,

  "DEFINE TABLE job_run TYPE NORMAL SCHEMAFULL;",
  "DEFINE FIELD organizationId ON job_run TYPE record<organization>;",
  "DEFINE FIELD jobType ON job_run TYPE string;",
  `DEFINE FIELD status ON job_run TYPE string DEFAULT "pending" ASSERT $value IN ["pending", "running", "completed", "failed"];`,
  "DEFINE FIELD startedAt ON job_run TYPE datetime DEFAULT time::now();",
  "DEFINE FIELD completedAt ON job_run TYPE option<datetime>;",
  "DEFINE FIELD error ON job_run TYPE option<string>;",
  "DEFINE FIELD metadata ON job_run TYPE option<object>;",

  "DEFINE TABLE audit_log TYPE NORMAL SCHEMAFULL;",
  "DEFINE FIELD organizationId ON audit_log TYPE record<organization>;",
  "DEFINE FIELD action ON audit_log TYPE string;",
  "DEFINE FIELD actorUserId ON audit_log TYPE record<canonical_user>;",
  "DEFINE FIELD targetType ON audit_log TYPE string;",
  "DEFINE FIELD targetId ON audit_log TYPE string;",
  "DEFINE FIELD previousValue ON audit_log TYPE option<any>;",
  "DEFINE FIELD newValue ON audit_log TYPE option<any>;",
  "DEFINE FIELD timestamp ON audit_log TYPE datetime DEFAULT time::now();",

  "DEFINE TABLE review_decision TYPE NORMAL SCHEMAFULL;",
  "DEFINE FIELD organizationId ON review_decision TYPE record<organization>;",
  "DEFINE FIELD reviewerId ON review_decision TYPE record<canonical_user>;",
  `DEFINE FIELD targetType ON review_decision TYPE string ASSERT $value IN ["work-unit", "summary", "identity", "mapping"];`,
  "DEFINE FIELD targetId ON review_decision TYPE string;",
  `DEFINE FIELD decision ON review_decision TYPE string ASSERT $value IN ["approved", "flagged", "rejected"];`,
  "DEFINE FIELD note ON review_decision TYPE option<string>;",
  "DEFINE FIELD timestamp ON review_decision TYPE datetime DEFAULT time::now();",

  "DEFINE TABLE recompute_request TYPE NORMAL SCHEMAFULL;",
  "DEFINE FIELD organizationId ON recompute_request TYPE record<organization>;",
  `DEFINE FIELD level ON recompute_request TYPE string ASSERT $value IN ["enrichment", "session", "cluster", "work-unit", "summary"];`,
  "DEFINE FIELD scope ON recompute_request TYPE object FLEXIBLE;",
  "DEFINE FIELD requestedBy ON recompute_request TYPE record<canonical_user>;",
  "DEFINE FIELD requestedAt ON recompute_request TYPE datetime DEFAULT time::now();",
  "DEFINE FIELD completedAt ON recompute_request TYPE option<datetime>;",
  `DEFINE FIELD status ON recompute_request TYPE string DEFAULT "pending" ASSERT $value IN ["pending", "running", "completed", "failed"];`,
] as const;
